# Generated by Django 3.2 on 2025-03-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0007_auto_20250301_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='created_at',
        ),
    ]
