# Generated by Django 3.2 on 2025-03-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0011_course_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sem_course_id', models.CharField(max_length=255, unique=True)),
                ('max_students', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.course', to_field='course_id')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AddField(
            model_name='semcourses',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.semester'),
        ),
    ]
