# Generated by Django 3.2 on 2025-03-01 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0006_campus_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='campus',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
        migrations.RemoveField(
            model_name='university',
            name='established_date',
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_id',
            field=models.CharField(default='TEMP_ID', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='uni_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='UMS.university', to_field='uni_id'),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
